import type { Content } from './types';

export const en: Content = {
  meta: {
    siteName: 'Meiko Trans Polska',
    titleSuffix: 'Meiko Trans Polska',
    description: 'Your complete logistics partner: freight forwarding, transport, warehousing and customs. Gliwice, Dąbrowa Górnicza, worldwide.',
  },
  nav: [
    { label: 'Services', key: 'services' },
    { label: 'About', key: 'about' },
    { label: 'Warehouses', key: 'svcWarehousing' },
    { label: 'Contact', key: 'contact' },
  ],
  cta: { quote: 'Request a quotation', services: 'See services', more: 'More', allServices: 'All services', back: 'Back to home', details: 'Details' },
  hero: {
    eyebrow: 'Meiko Trans Polska · part of Meiko Group since 1949',
    h1: 'Your complete logistics partner.',
    sub: 'Freight forwarding, transport, warehousing and customs in one place. Gliwice, Dąbrowa Górnicza, worldwide.',
  },
  proof: [
    { label: 'Meiko Group heritage since', factKey: 'since' },
    { label: 'Certifications', factKey: 'certs' },
    { label: 'People on the team', factKey: 'team' },
    { label: 'Warehouse space', factKey: 'sqm' },
  ],
  services: {
    title: 'One contract, the whole supply chain.',
    lead: 'The four services customers order most. Each with its own team, one shared system and a single contact person on your side.',
    homeTiles: [
      { key: 'svcForwarding', name: 'Freight forwarding', short: 'Road, air and ocean shipments organised by one person who owns your order.' },
      { key: 'svcWarehousing', name: 'Warehousing', short: 'Three warehouses in Silesia, high-bay racking, bonded storage, ADR class 8 and 9.' },
      { key: 'svcTransport', name: 'International transport', short: 'A network of proven carriers across Europe plus air and ocean freight.' },
      { key: 'svcWarehousing', hash: '#cross-docking', name: 'Cross-docking', short: 'Transhipment without storage: goods arrive and leave the same day.' },
    ],
    secondRowTitle: 'Supporting services',
    secondRow: [
      { name: 'Domestic transport', text: 'Distribution across Poland with our own orders and regular carriers.' },
      { name: 'Value-added services', text: 'Packing, re-packing, labelling, kitting and quality inspection.' },
      { name: 'Inventory management', text: 'Stock kept in our WMS with online visibility and customer reports.' },
      { name: 'Customer-specific projects', text: 'Solutions built around one production line or contract, with their own schedule.' },
      { name: 'Distribution', text: 'Deliveries to a network of recipients from a single consolidation point.' },
      { name: 'Contract logistics', text: 'Long-term warehousing and transport on terms agreed in one contract.' },
    ],
    crossDocking: {
      title: 'Cross-docking',
      text: 'We receive, sort and dispatch goods without putting them on a rack. That shortens delivery time and cuts storage cost. Handled in Gliwice, in a zone with direct dock access.',
    },
    key: [
      {
        key: 'svcForwarding', slug: 'spedycja', name: 'Freight forwarding',
        short: 'Road, air and ocean shipments organised by one person who owns your order.',
        lead: 'We plan and supervise the shipment from pickup to delivery. You talk to one person; we talk to carriers, ports, airports and customs.',
        image: '/media/gen-forwarding.jpg',
        params: [
          { label: 'Partner carriers', factKey: 'carrierPartners' },
          { label: 'Countries served', factKey: 'countries' },
          { label: 'Customs clearances a month', factKey: 'customsPerMonth' },
        ],
        benefits: [
          { title: 'One contact person', text: 'Your order owner knows your shipments and answers questions without passing you on.' },
          { title: 'Every transport mode', text: 'Road, air, sea and customs in one order, without separate contracts with several companies.' },
          { title: 'Japanese process discipline', text: 'Every stage has a checkpoint in the system. You see the status before you have to ask.' },
        ],
        faq: [
          { q: 'What does freight forwarding cover?', a: 'Choice of transport mode, carrier booking, shipping documents, cargo insurance on request, customs clearance and delivery supervision.' },
          { q: 'Where do we operate?', a: 'From Gliwice we cover Poland and Europe by road, and overseas destinations through the ports of Gdańsk, Hamburg and Antwerp and the airports in Katowice, Warsaw and Frankfurt.' },
          { q: 'How long does a quote take?', a: 'We answer a standard enquiry as soon as possible, usually the same day. Multi-stage projects are agreed in a meeting.' },
        ],
      },
      {
        key: 'svcTransport', slug: 'transport', name: 'International transport',
        short: 'A network of proven carriers across Europe plus air and ocean freight.',
        lead: 'Road transport across Europe with long-standing partners, and for farther destinations air and ocean freight through ports and airports we have worked with for years.',
        image: '/media/gen-transport.jpg',
        params: [
          { label: 'Partner carriers', factKey: 'carrierPartners' },
          { label: 'Countries served', factKey: 'countries' },
          { label: 'In Poland since', factKey: 'inPolandSince' },
        ],
        benefits: [
          { title: 'European road transport', text: 'Full and part loads, standard and specialised trailers, a stable pool of carriers.' },
          { title: 'Air freight', text: 'Bookings through a global network of airline partners, handling at Katowice, Warsaw and the main European hubs.' },
          { title: 'Ocean freight', text: 'FCL and LCL containers through Gdańsk, Gdynia, Hamburg, Bremerhaven, Antwerp and Rotterdam.' },
        ],
        faq: [
          { q: 'What cargo do we carry?', a: 'Industrial goods, production components, spare parts, palletised and big-bag cargo, as well as ADR class 8 and 9 loads.' },
          { q: 'Where do we operate?', a: 'All of Europe by road. Overseas through Baltic and North Sea ports and airports in Poland and Germany.' },
          { q: 'How long does a quote take?', a: 'Road transport is priced as soon as possible. Air and ocean freight depend on carrier availability.' },
        ],
      },
      {
        key: 'svcWarehousing', slug: 'magazynowanie', name: 'Warehousing',
        short: 'Three warehouses in Silesia, high-bay racking, bonded storage, ADR class 8 and 9.',
        lead: 'Two warehouses in Gliwice within the Katowice Special Economic Zone and a third under construction in Dąbrowa Górnicza. High-bay racking, bonded storage, an ADR zone and a WMS with live stock visibility.',
        image: '/media/still-aisle.jpg',
        params: [
          { label: 'Total floor space', factKey: 'sqm' },
          { label: 'Pallet spaces', factKey: 'pallets' },
          { label: 'Loading docks', factKey: 'docks' },
          { label: 'Warehouse 3 launch', factKey: 'wh3Start' },
        ],
        benefits: [
          { title: 'Bonded warehouse', text: 'Store goods without paying duty and VAT until they are released to the market.' },
          { title: 'ADR class 8 and 9', text: 'A certified zone for corrosive and other hazardous materials, with its own procedures.' },
          { title: 'WMS with online visibility', text: 'Stock, movements and reports available to the customer in real time, full batch traceability.' },
        ],
        faq: [
          { q: 'What does warehousing cover?', a: 'Receiving, high-bay or block storage, picking, packing, labelling, cross-docking and dispatch. Optionally bonded storage and an ADR zone.' },
          { q: 'Where are the warehouses?', a: 'Two in Gliwice at the A1/A4 junction and a third in Dąbrowa Górnicza, under construction, with launch planned for June 2027.' },
          { q: 'How long does a quote take?', a: 'We price space and handling as soon as possible after receiving your goods and volume data.' },
        ],
      },
    ],
  },
  audiences: {
    title: 'Who we work for',
    lead: 'Companies that need one partner instead of several subcontractors.',
    items: [
      { title: 'Manufacturers', text: 'Production line supply, component storage and finished-goods dispatch in one process.' },
      { title: 'Retail and distribution', text: 'Consolidated inbound, buffer storage and regular distribution to delivery points.' },
      { title: 'Business partners', text: 'Forwarders and logistics operators who need warehousing and customs capacity in Silesia.' },
    ],
  },
  why: {
    title: 'Why Meiko',
    kanji: '絆',
    kanjiMeaning: 'kizuna · bond',
    items: [
      { trait: 'Experienced', fact: 'Meiko Group has worked in logistics since 1949, in Poland since 2005. The processes we run in Gliwice were proven earlier in Nagoya, Chicago and Antwerp.' },
      { trait: 'Customer-focused', fact: 'Every customer has one contact person. We answer enquiries as soon as possible.' },
      { trait: 'Reliable', fact: 'ISO 9001:2015 quality system and AEO status granted by the customs administration. Both audited, both available on request.' },
    ],
  },
  warehouses: {
    title: 'Three warehouses in Silesia',
    lead: 'Two operating in Gliwice and a third under construction in Dąbrowa Górnicza. All next to the A1 and A4 motorways.',
    renderPlaceholder: 'Visualisation · to be generated',
    mapPlaceholder: 'Map · Google Maps at launch',
    launchNote: 'Operational launch planned for June 2027. Construction is under way and space reservations are open.',
    featuresTitle: 'What the site offers',
    distancesTitle: 'Distances',
    distances: [
      { place: 'A1 and A4 motorways', km: '5 km' },
      { place: 'Katowice Airport', km: '50 km' },
      { place: 'Ostrava', km: '70 km' },
      { place: 'Kraków', km: '85 km' },
      { place: 'Warsaw', km: '315 km' },
      { place: 'Ports of Gdańsk and Gdynia', km: '580 km' },
      { place: 'Hamburg', km: '900 km' },
      { place: 'Antwerp', km: '1,180 km' },
    ],
    items: [
      {
        key: 'whGliwice1', name: 'Warehouse 1', city: 'Gliwice', address: 'ul. Leona Wyczółkowskiego 121, 44-109 Gliwice',
        lead: 'The main site in the Katowice Special Economic Zone. High-bay racking, bonded storage and the forwarding office.',
        image: '/media/still-aerial.jpg',
        params: [{ label: 'Floor space', factKey: 'wh1Sqm' }, { label: 'Pallet spaces', factKey: 'wh1Pallets' }, { label: 'Loading docks', factKey: 'wh1Docks' }],
        features: ['High-bay racking', 'Bonded warehouse', 'ADR class 8 and 9 zone', 'WMS', 'Forwarding office and customs agency on site'],
      },
      {
        key: 'whGliwice2', name: 'Warehouse 2', city: 'Gliwice', address: 'ul. Gaudiego 6D, 44-109 Gliwice',
        lead: 'The second Gliwice site, minutes from the first. Cross-docking, value-added services and domestic distribution.',
        image: '/media/still-wall-logo.jpg',
        params: [{ label: 'Floor space', factKey: 'wh2Sqm' }, { label: 'Pallet spaces', factKey: 'wh2Pallets' }, { label: 'Loading docks', factKey: 'wh2Docks' }],
        features: ['Cross-docking zone', 'Packing and labelling', 'Kitting', 'WMS', 'Domestic distribution'],
      },
      {
        key: 'whDabrowa', name: 'Warehouse 3', city: 'Dąbrowa Górnicza', address: 'ul. Innowacyjna, 42-520 Dąbrowa Górnicza',
        lead: 'A new investment. The largest Meiko site in Poland, designed for contract logistics and bonded storage.',
        badge: 'launch 06.2027',
        image: '/media/wh3-render.jpg',
        params: [{ label: 'Floor space', factKey: 'wh3Sqm' }, { label: 'Pallet spaces', factKey: 'wh3Pallets' }, { label: 'Loading docks', factKey: 'wh3Docks' }],
        features: ['17 docks, including 2 zero-level gates', 'Integrated WMS', 'Bonded warehouse', 'Space for customer-specific projects'],
      },
    ],
  },
  certs: {
    title: 'Quality and certifications',
    zoom: 'Enlarge certificate',
    lead: 'Three documents that say more than declarations. Click to see the original.',
    items: [
      { code: 'ISO 9001:2015', name: 'Quality management system', text: 'PN-EN ISO 9001:2015 certificate no. 2456/07/2024/J/R issued by Polska Akademia Jakości Cert for both Gliwice sites. Scope: international and domestic forwarding and logistics services. Valid until 20.07.2027.', image: '/media/cert-iso.jpg' },
      { code: 'AEO', name: 'Authorised Economic Operator', text: 'AEO authorisation no. PLAEOF330000190092 issued by the Director of the Tax Administration Chamber in Katowice, in force since 23.12.2019. Scope: customs simplifications plus security and safety.', image: '/media/cert-aeo.jpg' },
      { code: 'Quality policy', name: 'Management commitment', text: 'Goals: zero non-conformities, higher customer satisfaction and trust, staff training and development, compliance with legal and regulatory requirements. Signed by the CEO on 01.10.2022.', image: '/media/cert-policy.jpg' },
    ],
  },
  depts: {
    title: 'Reach the right department',
    lead: 'No switchboard, no transfers. You call the people who will handle your case.',
    items: [
      { name: 'Forwarding', phone: '+48 32 000 00 01', email: 'spedycja@meikotrans.com.pl' },
      { name: 'Warehouse', phone: '+48 32 000 00 02', email: 'magazyn@meikotrans.com.pl' },
      { name: 'Customs agency', phone: '+48 32 000 00 03', email: 'clo@meikotrans.com.pl' },
      { name: 'Office', phone: '+48 32 000 00 00', email: 'biuro@meikotrans.com.pl' },
    ],
  },
  quoteBand: {
    title: 'Tell us what you ship and from where. We do the maths.',
    lead: 'Three fields. We reply as soon as possible.',
  },
  quote: {
    title: 'Request a quotation',
    lead: 'Three fields. We reply as soon as possible.',
    reply: 'We reply as soon as possible.',
    fields: { contact: 'Contact person', email: 'Email address', service: 'Requested service', company: 'Company name', phone: 'Telephone', cargo: 'Cargo type' },
    servicePlaceholder: 'Choose a service',
    submit: 'Send the request',
    success: { title: 'Thank you. Your request has arrived.', text: 'Your order owner will get back to you as soon as possible by email or phone.' },
    errors: { required: 'This field is required.', email: 'Enter a valid email address.' },
    flow: {
      title: 'Tell us what you need. We take care of the rest.',
      lead: 'Three fields. Your order owner gets back to you as soon as possible.',
      after: ['You write a few words about the cargo', 'We analyse the route and requirements', 'We reply as soon as possible with a quote'],
      cardTitle: 'Request a quote',
      cardLead: 'A few words are enough, we settle the rest in a call.',
      service: 'Service',
      services: [
        { slug: 'transport', name: 'Transport', icon: 'truck' },
        { slug: 'magazynowanie', name: 'Warehousing', icon: 'warehouse' },
        { slug: 'spedycja', name: 'Forwarding', icon: 'ship' },
        { slug: 'clo', name: 'Customs', icon: 'customs' },
      ],
      who: 'Full name', whoPh: 'e.g. Anna Kowal',
      reach: 'Email or phone', reachPh: 'e.g. anna@company.com or +48 600 000 000',
      desc: 'What is it about', descPh: 'e.g. 12 pallets of components from Gliwice to Brno, once a week',
    },
  },
  about: {
    title: 'Japanese precision. A Silesian address.',
    lead: 'Meiko Trans Polska is part of Meiko Trans Co., Ltd. of Nagoya, which has run logistics operations across Asia, the Americas and Europe since 1949. We have operated in Poland since 2005.',
    group: {
      title: 'Meiko Group',
      text: 'The parent company Meiko Trans Co., Ltd. was founded on 22 January 1949 in Nagoya. Today the group has offices in Japan, the United States, Mexico, Europe, India, Thailand, China, Vietnam and Hong Kong. The Polish company serves customers across Europe from the Katowice Special Economic Zone.',
      facts: [{ label: 'Founded', value: '22.01.1949' }, { label: 'Group headquarters', value: 'Nagoya, Japan' }, { label: 'In Poland since', value: '2005' }, { label: 'Locations in Poland', value: 'Gliwice, Dąbrowa Górnicza' }],
    },
    timelineTitle: 'From a local branch to a logistics hub',
    timeline: [
      { era: '2005-2016', title: 'Building the foundation', text: 'Opening the Gliwice branch and launching warehousing and forwarding operations.' },
      { era: '2018-2023', title: 'Quality and customs expertise', text: 'ISO 9001 certification, AEO status, our own customs agency and bonded warehouse.' },
      { era: '2025-2027', title: 'Investment and technology', text: 'Construction of the third warehouse in Dąbrowa Górnicza and digital systems for customers and drivers.' },
    ],
    valuesTitle: 'Values we brought from Japan',
    valuesLead: 'Not slogans on a wall but a way of working: accuracy, responsibility and long relationships.',
    values: [
      { kanji: '絆', romaji: 'kizuna', meaning: 'Bond. We build customer relationships for years, not for one order.' },
      { kanji: 'おもてなし', romaji: 'omotenashi', meaning: 'Hospitality. We anticipate needs before they are spoken.' },
      { kanji: '誠実', romaji: 'seijitsu', meaning: 'Integrity. We say what we can do, and do what we said.' },
      { kanji: '和', romaji: 'wa', meaning: 'Harmony. Team, carriers and customer work to one rhythm.' },
      { kanji: '信頼', romaji: 'shinrai', meaning: 'Trust. Earned with every delivery, confirmed by audits.' },
    ],
    network: {
      title: 'A global network. Local expertise.',
      lead: 'One integrated solution across three continents.',
      regions: [
        { name: 'Japan', cities: 'Nagoya, Tokyo, Osaka, Kobe, Fukuoka, Sendai, Hamamatsu' },
        { name: 'North America', cities: 'Los Angeles, Chicago, Houston, Atlanta, Ohio, South Carolina' },
        { name: 'Mexico', cities: 'Guanajuato' },
        { name: 'Europe', cities: 'Antwerp, Grobbendonk, Düsseldorf, Hamburg' },
        { name: 'Poland', cities: 'Gliwice, Dąbrowa Górnicza' },
        { name: 'India', cities: 'Chennai, Gurgaon' },
        { name: 'Thailand', cities: 'Bangkok, Laem Chabang, Suvarnabhumi' },
        { name: 'China and Hong Kong', cities: 'Shanghai, Guangzhou, Suzhou, Hong Kong' },
        { name: 'Vietnam', cities: 'Hanoi, Ho Chi Minh City' },
      ],
    },
  },
  quality: {
    title: 'Quality and certifications',
    lead: 'ISO 9001:2015 certificate, AEO authorisation and a quality policy signed by the board. Click a document to see the original. Below, what they mean for the customer.',
    stats: { aeo: 'AEO status held continuously since', iso: 'ISO 9001 certificate valid until', sites: 'certified sites in Gliwice' },
    outcomesTitle: 'What it means in practice',
    outcomes: [
      { title: 'Consistent quality', text: 'Every order passes the same checkpoints, whoever handles it.' },
      { title: 'Documented processes', text: 'Procedures written down, audited and updated. A new colleague works by the same rules.' },
      { title: 'Continuous improvement', text: 'We measure punctuality and errors and turn the results into process changes.' },
      { title: 'Customs security', text: 'AEO status requires access control, records and supply chain safeguards. We meet them every day.' },
      { title: 'Compliance', text: 'Full compliance with customs and tax law, confirmed by the customs administration.' },
      { title: 'Trusted operator', text: 'Customs authorities treat an AEO as a low-risk partner. For the customer that means fewer inspections and stoppages.' },
      { title: 'Faster clearances', text: 'Customs simplifications and priority handling shorten the time from border to warehouse.' },
      { title: 'Risk management', text: 'We identify operational risks in advance and keep action plans for them.' },
    ],
  },
  contact: {
    title: 'Contact',
    lead: 'Pick a department or a location. We answer 8:00-16:00 CET on working days.',
    locationsTitle: 'Locations',
    locations: [
      { name: 'Head office and Warehouse 1 · Gliwice', address: 'ul. Leona Wyczółkowskiego 121, 44-109 Gliwice, Poland' },
      { name: 'Warehouse 2 · Gliwice', address: 'ul. Gaudiego 6D, 44-109 Gliwice, Poland' },
      { name: 'Warehouse 3 · Dąbrowa Górnicza (under construction)', address: 'ul. Innowacyjna, 42-520 Dąbrowa Górnicza, Poland' },
    ],
  },
  footer: {
    legal: 'Meiko Trans Polska Sp. z o.o. · company registration details to be added before publication',
    docs: ['Privacy policy', 'Cookie policy', 'Company details'],
    pagesTitle: 'Pages',
    docsTitle: 'Documents',
    langTitle: 'Language',
    note: 'Part of Meiko Trans Co., Ltd., Nagoya, Japan.',
    address: 'ul. Leona Wyczółkowskiego 121, 44-109 Gliwice, Poland',
  },
  faqTitle: 'Questions and answers',
  approval: { tooltip: 'Sample value, to be approved before publication', legend: 'value to be approved' },
  notFound: { title: 'This page does not exist.', text: 'The address may have changed. Go back to the home page and pick from the menu.' },
};
