export const homeCopy = {
  pl: {
    title: ['Twój biznes w ruchu.', 'Logistyka po naszej stronie.'],
    intro: 'Łączymy transport, magazynowanie i obsługę celną. Od pierwszego odbioru po ostatnią dostawę, z jednym partnerem, który zna Twój biznes.',
    location: 'Gliwice, Polska', reach: 'Lokalny zespół. Globalna sieć Meiko.', pause: 'Wstrzymaj film', play: 'Odtwórz film',
    proof: ['Początek grupy Meiko', 'Działamy w Polsce', 'System zarządzania jakością', 'Status celny'], servicesTitle: 'Każdy etap dostawy.\nJeden partner.',
    servicesLead: 'Potrzebujesz pojedynczego przewozu czy stałej obsługi logistycznej? Dobierzemy zakres do Twojego ładunku, kierunku i skali działania.',
    services: [
      { title: 'Spedycja', text: 'Planujemy trasę, koordynujemy przewoźników i dokumenty. Ty kontaktujesz się z jednym opiekunem.' },
      { title: 'Magazynowanie', text: 'Przyjęcie, składowanie, kompletacja i wysyłka. Zaplecze w Gliwicach z obsługą w systemie WMS.' },
      { title: 'Transport międzynarodowy', text: 'Łączymy europejskie trasy drogowe z frachtem morskim i lotniczym na dalszych kierunkach.' },
      { title: 'Cross-docking', text: 'Przyjmujemy, sortujemy i wysyłamy towar dalej, bez odkładania na regał. Mniej etapów po drodze.' },
    ],
    customs: 'A co z formalnościami?', customsText: 'Obsługę przewozu uzupełniamy o odprawy i skład celny.', customsLink: 'Poznaj zakres spedycji',
    audienceLabel: 'Twoja branża', audienceTitle: 'Logistyka dopasowana\ndo rytmu Twojej firmy.',
    audienceLead: 'Wybierz profil działalności i zobacz, jak możemy wesprzeć Twój łańcuch dostaw.',
    audiences: [
      { name: 'Produkcja', title: 'Od komponentów po gotowy produkt.', text: 'Łączymy dostawy do produkcji z magazynowaniem i wysyłką wyrobów gotowych. Poszczególne etapy planujemy jako jeden proces.', points: ['Zaopatrzenie linii produkcyjnych', 'Magazynowanie komponentów', 'Wysyłka wyrobów gotowych'] },
      { name: 'Handel i dystrybucja', title: 'Towar gotowy na kolejny etap.', text: 'Konsolidujemy dostawy, przechowujemy zapasy i przygotowujemy zamówienia do dystrybucji. Zakres obsługi dopasowujemy do sieci Twoich odbiorców.', points: ['Konsolidacja dostaw', 'Kompletacja i pakowanie', 'Dystrybucja do punktów odbioru'] },
      { name: 'Operatorzy logistyczni', title: 'Twoje zaplecze na Śląsku.', text: 'Wspieramy spedytorów i operatorów, którzy potrzebują lokalnego partnera. Udostępniamy zaplecze magazynowe, przeładunkowe i celne.', points: ['Obsługa magazynowa', 'Przeładunki i cross-docking', 'Wsparcie w formalnościach celnych'] },
    ],
    solution: 'Porozmawiajmy o Twoim projekcie', warehouseTitle: 'Blisko Twoich dostaw.\nGotowi na rozwój.',
    warehouseLead: 'Dwa działające magazyny w Gliwicach i nowa inwestycja w Dąbrowie Górniczej. Wybierz lokalizację i poznaj jej możliwości.',
    operational: 'Obiekt operacyjny', planned: 'W budowie, start 06.2027', render: 'Wizualizacja inwestycji',
    warehouseTags: ['Skład celny · magazynowanie', 'Cross-docking · dystrybucja', '19 000 m² planowanej powierzchni'], whyTitle: 'Japońskie korzenie.\nZespół blisko Ciebie.',
    whyIntro: 'Jesteśmy częścią grupy Meiko z Nagoi, działającej od 1949 roku. W Polsce od 2005 roku łączymy międzynarodowe doświadczenie z lokalną znajomością logistyki.',
    why: [
      { title: 'Jedna osoba kontaktowa', text: 'Opiekun zna Twoje zlecenie i koordynuje kolejne etapy obsługi.' },
      { title: 'Wspólny standard pracy', text: 'System ISO 9001:2015 i status AEO wspierają jakość procesów oraz obsługę celną.' },
    ],
    aboutLink: 'Poznaj nasz zespół i grupę', teamCaption: 'Meiko Trans Polska / Gliwice', qualityTitle: 'Zaufanie oparte na procesach.', contactTitle: 'Dokąd zmierza\nTwój biznes?',
    contactLead: 'Opowiedz nam o swoim ładunku i potrzebach. Przygotujemy zakres obsługi dopasowany do Twojej firmy.', contactLink: 'Dane kontaktowe',
    steps: [
      { title: 'Opisz potrzeby', text: 'Podaj rodzaj towaru, wolumen i kierunek dostawy lub zakres magazynowania.' },
      { title: 'Ustalmy rozwiązanie', text: 'Doprecyzujemy szczegóły i dobierzemy usługi do Twojego procesu.' },
      { title: 'Poznaj ofertę', text: 'Otrzymasz propozycję zakresu współpracy i warunków realizacji.' },
    ],
  },
  en: {
    title: ['Your business in motion.', 'Your logistics in our hands.'],
    intro: 'Transport, warehousing and customs, connected. From the first collection to the final delivery, with one partner who understands your business.',
    location: 'Gliwice, Poland', reach: 'A local team. The global Meiko network.', pause: 'Pause video', play: 'Play video',
    proof: ['Meiko Group established', 'Operating in Poland since', 'Quality management system', 'Customs status'], servicesTitle: 'Every stage of delivery.\nOne partner.',
    servicesLead: 'A single shipment or ongoing logistics support? We tailor the scope to your cargo, destination and scale of operations.',
    services: [
      { title: 'Freight forwarding', text: 'We plan routes and coordinate carriers and documents. You speak to one dedicated contact.' },
      { title: 'Warehousing', text: 'Receiving, storage, picking and dispatch. Facilities in Gliwice supported by our WMS.' },
      { title: 'International transport', text: 'We connect European road routes with ocean and air freight for destinations further afield.' },
      { title: 'Cross-docking', text: 'We receive, sort and dispatch your goods without putting them into storage. Fewer steps along the way.' },
    ],
    customs: 'What about the paperwork?', customsText: 'Customs clearance and bonded storage complement our freight services.', customsLink: 'Explore freight forwarding',
    audienceLabel: 'Your industry', audienceTitle: 'Logistics that fit\nthe pace of your business.', audienceLead: 'Choose your business profile to see how we can support your supply chain.',
    audiences: [
      { name: 'Manufacturing', title: 'From components to finished goods.', text: 'We connect inbound production supplies with storage and outbound deliveries, planning each stage as part of a single process.', points: ['Production line supply', 'Component storage', 'Finished goods dispatch'] },
      { name: 'Retail & distribution', title: 'Ready for the next destination.', text: 'We consolidate deliveries, store inventory and prepare orders for distribution. Our service is tailored to your network of recipients.', points: ['Delivery consolidation', 'Picking and packing', 'Distribution to recipients'] },
      { name: 'Logistics operators', title: 'Your local base in Silesia.', text: 'We support forwarders and operators who need a local partner, providing warehousing, transhipment and customs support.', points: ['Warehousing support', 'Transhipment and cross-docking', 'Customs support'] },
    ],
    solution: 'Let’s discuss your project', warehouseTitle: 'Close to your deliveries.\nReady for growth.',
    warehouseLead: 'Two operating warehouses in Gliwice and a new development in Dąbrowa Górnicza. Explore each location and its capabilities.',
    operational: 'Operational facility', planned: 'Under construction, launch 06.2027', render: 'Development visualisation',
    warehouseTags: ['Bonded storage · warehousing', 'Cross-docking · distribution', '19,000 m² of planned floor space'], whyTitle: 'Japanese roots.\nA team close to you.',
    whyIntro: 'We are part of the Nagoya-based Meiko Group, established in 1949. Since 2005, our Polish team has combined international experience with local logistics knowledge.',
    why: [
      { title: 'One point of contact', text: 'Your coordinator knows your shipment and connects every stage of the service.' },
      { title: 'A shared working standard', text: 'ISO 9001:2015 and AEO status support process quality and customs operations.' },
    ],
    aboutLink: 'Meet our team and group', teamCaption: 'Meiko Trans Polska / Gliwice', qualityTitle: 'Trust built on clear processes.', contactTitle: 'Where is your\nbusiness heading?',
    contactLead: 'Tell us about your cargo and requirements. We will prepare a scope of services that fits your business.', contactLink: 'Contact details',
    steps: [
      { title: 'Tell us what you need', text: 'Share your cargo type, volume and destination or storage requirements.' },
      { title: 'Shape the solution', text: 'We clarify the details and match our services to your process.' },
      { title: 'Review your offer', text: 'Receive a proposed scope of cooperation and delivery terms.' },
    ],
  },
};
