import type { Content } from './types';

export const pl: Content = {
  meta: {
    siteName: 'Meiko Trans Polska',
    titleSuffix: 'Meiko Trans Polska',
    description: 'Kompletny partner logistyczny: spedycja, transport, magazynowanie i obsługa celna. Gliwice, Dąbrowa Górnicza, świat.',
  },
  nav: [
    { label: 'Usługi', key: 'services' },
    { label: 'O firmie', key: 'about' },
    { label: 'Magazyny', key: 'svcWarehousing' },
    { label: 'Kontakt', key: 'contact' },
  ],
  cta: { quote: 'Zapytaj o ofertę', services: 'Zobacz usługi', more: 'Więcej', allServices: 'Wszystkie usługi', back: 'Wróć na stronę główną', details: 'Szczegóły' },
  hero: {
    eyebrow: 'Meiko Trans Polska · w grupie Meiko od 1949',
    h1: 'Kompletny partner logistyczny.',
    sub: 'Spedycja, transport, magazynowanie i cło w jednym miejscu. Gliwice, Dąbrowa Górnicza, świat.',
  },
  proof: [
    { label: 'Tradycja grupy Meiko od', factKey: 'since' },
    { label: 'Certyfikaty', factKey: 'certs' },
    { label: 'Osób w zespole', factKey: 'team' },
    { label: 'Powierzchni magazynowej', factKey: 'sqm' },
  ],
  services: {
    title: 'Jedna umowa, cały łańcuch dostaw.',
    lead: 'Cztery usługi, które klienci zamawiają najczęściej. Każda z własnym zespołem, wspólnym systemem i jedną osobą kontaktową po Twojej stronie.',
    homeTiles: [
      { key: 'svcForwarding', name: 'Spedycja', short: 'Organizacja przewozu drogowego, lotniczego i morskiego z jednym opiekunem zlecenia.' },
      { key: 'svcWarehousing', name: 'Magazynowanie', short: 'Trzy magazyny na Śląsku, regały wysokiego składowania, skład celny, ADR 8 i 9.' },
      { key: 'svcTransport', name: 'Transport międzynarodowy', short: 'Sieć sprawdzonych przewoźników w Europie oraz fracht lotniczy i morski.' },
      { key: 'svcWarehousing', hash: '#cross-docking', name: 'Cross-docking', short: 'Przeładunek bez składowania: towar wjeżdża i wyjeżdża tego samego dnia.' },
    ],
    secondRowTitle: 'Usługi uzupełniające',
    secondRow: [
      { name: 'Transport krajowy', text: 'Dystrybucja na terenie Polski w oparciu o własne zlecenia i stałych przewoźników.' },
      { name: 'Usługi dodane (VAS)', text: 'Pakowanie, przepakowanie, etykietowanie, kompletacja zestawów, kontrola jakości.' },
      { name: 'Zarządzanie zapasami', text: 'Prowadzenie stanów w systemie WMS z podglądem online i raportami dla klienta.' },
      { name: 'Projekty dedykowane', text: 'Rozwiązania pod konkretną linię produkcyjną lub kontrakt, z własnym harmonogramem.' },
      { name: 'Dystrybucja', text: 'Dostawy do sieci odbiorców z jednego punktu konsolidacji.' },
      { name: 'Logistyka kontraktowa', text: 'Długoterminowa obsługa magazynowo-transportowa na zasadach uzgodnionych w umowie.' },
    ],
    crossDocking: {
      title: 'Cross-docking',
      text: 'Towar przyjmujemy, sortujemy i wysyłamy dalej bez odkładania na regał. Skraca to czas dostawy i obniża koszt składowania. Realizujemy go w Gliwicach, w strefie z bezpośrednim dostępem do doków.',
    },
    key: [
      {
        key: 'svcForwarding', slug: 'spedycja', name: 'Spedycja',
        short: 'Organizacja przewozu drogowego, lotniczego i morskiego z jednym opiekunem zlecenia.',
        lead: 'Planujemy i nadzorujemy przewóz od odbioru do dostawy. Ty rozmawiasz z jedną osobą, my z przewoźnikami, portami, lotniskami i urzędem celnym.',
        image: '/media/gen-forwarding.jpg',
        params: [
          { label: 'Przewoźników partnerskich', factKey: 'carrierPartners' },
          { label: 'Krajów obsługi', factKey: 'countries' },
          { label: 'Odpraw celnych miesięcznie', factKey: 'customsPerMonth' },
        ],
        benefits: [
          { title: 'Jedna osoba kontaktowa', text: 'Opiekun zlecenia zna Twoje przesyłki i odpowiada na pytania bez przekazywania dalej.' },
          { title: 'Wszystkie gałęzie transportu', text: 'Droga, lotnisko, port i cło w jednym zleceniu, bez osobnych umów z kilkoma firmami.' },
          { title: 'Japońska dyscyplina procesu', text: 'Każdy etap ma swój punkt kontrolny w systemie. Widzisz status, zanim zapytasz.' },
        ],
        faq: [
          { q: 'Co obejmuje usługa spedycji?', a: 'Dobór środka transportu, rezerwację u przewoźnika, dokumenty przewozowe, ubezpieczenie ładunku na życzenie, odprawę celną i nadzór nad dostawą.' },
          { q: 'Gdzie działamy?', a: 'Z Gliwic obsługujemy Polskę i Europę transportem drogowym, a przez porty w Gdańsku, Hamburgu i Antwerpii oraz lotniska w Katowicach, Warszawie i Frankfurcie także kierunki zamorskie.' },
          { q: 'Jak długo trwa wycena?', a: 'Na standardowe zapytanie odpowiadamy jak najszybciej, zwykle tego samego dnia. Projekty wieloetapowe uzgadniamy na spotkaniu.' },
        ],
      },
      {
        key: 'svcTransport', slug: 'transport', name: 'Transport międzynarodowy',
        short: 'Sieć sprawdzonych przewoźników w Europie oraz fracht lotniczy i morski.',
        lead: 'Transport drogowy po Europie na bazie stałych partnerów, a dla dalszych kierunków fracht lotniczy i morski przez porty i lotniska, z którymi współpracujemy od lat.',
        image: '/media/gen-transport.jpg',
        params: [
          { label: 'Przewoźników partnerskich', factKey: 'carrierPartners' },
          { label: 'Krajów obsługi', factKey: 'countries' },
          { label: 'W Polsce od', factKey: 'inPolandSince' },
        ],
        benefits: [
          { title: 'Transport drogowy w Europie', text: 'Ładunki całopojazdowe i drobnicowe, naczepy standardowe i specjalistyczne, stała pula przewoźników.' },
          { title: 'Fracht lotniczy', text: 'Rezerwacje przez globalną sieć partnerów lotniczych, obsługa na Katowice, Warszawę i główne huby europejskie.' },
          { title: 'Fracht morski', text: 'Kontenery FCL i LCL przez Gdańsk, Gdynię, Hamburg, Bremerhaven, Antwerpię i Rotterdam.' },
        ],
        faq: [
          { q: 'Jakie ładunki przewozicie?', a: 'Towary przemysłowe, komponenty produkcyjne, części zamienne, towary paletyzowane i w big-bagach, a także ładunki ADR klasy 8 i 9.' },
          { q: 'Gdzie działamy?', a: 'Cała Europa transportem drogowym. Kierunki zamorskie przez porty Morza Bałtyckiego i Północnego oraz lotniska w Polsce i Niemczech.' },
          { q: 'Jak długo trwa wycena?', a: 'Transport drogowy wyceniamy jak najszybciej. Fracht lotniczy i morski zależy od dostępności przewoźnika.' },
        ],
      },
      {
        key: 'svcWarehousing', slug: 'magazynowanie', name: 'Magazynowanie',
        short: 'Trzy magazyny na Śląsku, regały wysokiego składowania, skład celny, ADR 8 i 9.',
        lead: 'Dwa magazyny w Gliwicach w Katowickiej Specjalnej Strefie Ekonomicznej i trzeci w budowie w Dąbrowie Górniczej. Regały wysokiego składowania, skład celny, strefa ADR i system WMS z podglądem stanów.',
        image: '/media/still-aisle.jpg',
        params: [
          { label: 'Powierzchni łącznie', factKey: 'sqm' },
          { label: 'Miejsc paletowych', factKey: 'pallets' },
          { label: 'Doków', factKey: 'docks' },
          { label: 'Magazyn 3: start', factKey: 'wh3Start' },
        ],
        benefits: [
          { title: 'Skład celny', text: 'Składowanie towaru bez natychmiastowej zapłaty cła i VAT, do momentu wprowadzenia na rynek.' },
          { title: 'ADR klasy 8 i 9', text: 'Certyfikowana strefa dla materiałów żrących i pozostałych niebezpiecznych, z własnymi procedurami.' },
          { title: 'WMS z podglądem online', text: 'Stany, ruchy i raporty dostępne dla klienta na bieżąco, pełna identyfikowalność partii.' },
        ],
        faq: [
          { q: 'Co obejmuje usługa magazynowania?', a: 'Przyjęcie, składowanie na regałach wysokich lub blokowo, kompletację, pakowanie, etykietowanie, cross-docking i wysyłkę. Opcjonalnie skład celny i strefę ADR.' },
          { q: 'Gdzie są magazyny?', a: 'Dwa w Gliwicach przy węźle A1 i A4 oraz trzeci w Dąbrowie Górniczej, w budowie, z planowanym startem w czerwcu 2027.' },
          { q: 'Jak długo trwa wycena?', a: 'Wycenę powierzchni i obsługi przygotowujemy jak najszybciej po otrzymaniu danych o towarze i wolumenach.' },
        ],
      },
    ],
  },
  audiences: {
    title: 'Dla kogo pracujemy',
    lead: 'Obsługujemy firmy, które potrzebują jednego partnera zamiast kilku podwykonawców.',
    items: [
      { title: 'Producenci', text: 'Zaopatrzenie linii produkcyjnych, magazyn komponentów i wysyłka wyrobów gotowych w jednym procesie.' },
      { title: 'Sieci handlowe i dystrybutorzy', text: 'Konsolidacja dostaw, magazyn buforowy i regularna dystrybucja do punktów odbioru.' },
      { title: 'Partnerzy biznesowi', text: 'Spedytorzy i operatorzy logistyczni, którzy potrzebują zaplecza magazynowego i celnego na Śląsku.' },
    ],
  },
  why: {
    title: 'Dlaczego Meiko',
    kanji: '絆',
    kanjiMeaning: 'kizuna · więź',
    items: [
      { trait: 'Doświadczeni', fact: 'Grupa Meiko działa w logistyce od 1949 roku, w Polsce od 2005. Procesy, które stosujemy w Gliwicach, sprawdziły się wcześniej w Nagoi, Chicago i Antwerpii.' },
      { trait: 'Zorientowani na klienta', fact: 'Każdy klient ma jedną osobę kontaktową. Na zapytania odpowiadamy jak najszybciej.' },
      { trait: 'Wiarygodni', fact: 'System jakości ISO 9001:2015 i status AEO nadany przez administrację celną. Oba audytowane, oba do wglądu.' },
    ],
  },
  warehouses: {
    title: 'Trzy magazyny na Śląsku',
    lead: 'Dwa działające w Gliwicach i trzeci w budowie w Dąbrowie Górniczej. Wszystkie przy autostradach A1 i A4.',
    renderPlaceholder: 'Wizualizacja · do wygenerowania',
    mapPlaceholder: 'Mapa · Google Maps przy wdrożeniu',
    launchNote: 'Start operacyjny planowany na czerwiec 2027. Trwa budowa, przyjmujemy rezerwacje powierzchni.',
    featuresTitle: 'Co oferuje obiekt',
    distancesTitle: 'Odległości',
    distances: [
      { place: 'Autostrady A1 i A4', km: '5 km' },
      { place: 'Lotnisko Katowice', km: '50 km' },
      { place: 'Ostrawa', km: '70 km' },
      { place: 'Kraków', km: '85 km' },
      { place: 'Warszawa', km: '315 km' },
      { place: 'Porty Gdańsk i Gdynia', km: '580 km' },
      { place: 'Hamburg', km: '900 km' },
      { place: 'Antwerpia', km: '1 180 km' },
    ],
    items: [
      {
        key: 'whGliwice1', name: 'Magazyn 1', city: 'Gliwice', address: 'ul. Leona Wyczółkowskiego 121, 44-109 Gliwice',
        lead: 'Główny obiekt w Katowickiej Specjalnej Strefie Ekonomicznej. Regały wysokiego składowania, skład celny i biuro spedycji.',
        image: '/media/still-aerial.jpg',
        params: [{ label: 'Powierzchnia', factKey: 'wh1Sqm' }, { label: 'Miejsc paletowych', factKey: 'wh1Pallets' }, { label: 'Doków', factKey: 'wh1Docks' }],
        features: ['Regały wysokiego składowania', 'Skład celny', 'Strefa ADR klasy 8 i 9', 'System WMS', 'Biuro spedycji i agencja celna na miejscu'],
      },
      {
        key: 'whGliwice2', name: 'Magazyn 2', city: 'Gliwice', address: 'ul. Gaudiego 6D, 44-109 Gliwice',
        lead: 'Drugi obiekt w Gliwicach, kilka minut od pierwszego. Cross-docking, usługi dodane i dystrybucja krajowa.',
        image: '/media/still-wall-logo.jpg',
        params: [{ label: 'Powierzchnia', factKey: 'wh2Sqm' }, { label: 'Miejsc paletowych', factKey: 'wh2Pallets' }, { label: 'Doków', factKey: 'wh2Docks' }],
        features: ['Strefa cross-dockingu', 'Pakowanie i etykietowanie', 'Kompletacja zestawów', 'System WMS', 'Dystrybucja krajowa'],
      },
      {
        key: 'whDabrowa', name: 'Magazyn 3', city: 'Dąbrowa Górnicza', address: 'ul. Innowacyjna, 42-520 Dąbrowa Górnicza',
        lead: 'Nowa inwestycja. Największy obiekt Meiko w Polsce, projektowany pod obsługę kontraktową i skład celny.',
        badge: 'start 06.2027',
        image: '/media/wh3-render.jpg',
        params: [{ label: 'Powierzchnia', factKey: 'wh3Sqm' }, { label: 'Miejsc paletowych', factKey: 'wh3Pallets' }, { label: 'Doków', factKey: 'wh3Docks' }],
        features: ['17 doków, w tym 2 bramy z poziomu zero', 'Zintegrowany system WMS', 'Skład celny', 'Powierzchnia pod projekty dedykowane'],
      },
    ],
  },
  certs: {
    title: 'Jakość i certyfikaty',
    zoom: 'Powiększ certyfikat',
    lead: 'Trzy dokumenty, które mówią więcej niż deklaracje. Kliknij, aby zobaczyć oryginał.',
    items: [
      { code: 'ISO 9001:2015', name: 'System zarządzania jakością', text: 'Certyfikat PN-EN ISO 9001:2015 nr 2456/07/2024/J/R wydany przez Polską Akademię Jakości Cert dla obu lokalizacji w Gliwicach. Zakres: międzynarodowe i krajowe usługi spedycyjno-logistyczne. Ważny do 20.07.2027.', image: '/media/cert-iso.jpg' },
      { code: 'AEO', name: 'Upoważniony przedsiębiorca', text: 'Pozwolenie AEO nr PLAEOF330000190092 wydane przez Dyrektora Izby Administracji Skarbowej w Katowicach, obowiązuje od 23.12.2019. Zakres: uproszczenia celne oraz bezpieczeństwo i ochrona.', image: '/media/cert-aeo.jpg' },
      { code: 'Polityka jakości', name: 'Zobowiązanie zarządu', text: 'Cele: zero niezgodności, poprawa satysfakcji i zaufania klienta, szkolenie i rozwój pracowników, zgodność z wymaganiami prawnymi i regulacyjnymi. Podpisana przez prezesa zarządu 01.10.2022.', image: '/media/cert-policy.jpg' },
    ],
  },
  depts: {
    title: 'Kontakt do właściwego działu',
    lead: 'Bez centrali i przekierowań. Dzwonisz do osób, które zajmą się Twoją sprawą.',
    items: [
      { name: 'Spedycja', phone: '+48 32 000 00 01', email: 'spedycja@meikotrans.com.pl' },
      { name: 'Magazyn', phone: '+48 32 000 00 02', email: 'magazyn@meikotrans.com.pl' },
      { name: 'Agencja celna', phone: '+48 32 000 00 03', email: 'clo@meikotrans.com.pl' },
      { name: 'Biuro', phone: '+48 32 000 00 00', email: 'biuro@meikotrans.com.pl' },
    ],
  },
  quoteBand: {
    title: 'Opisz, co i skąd wysyłasz. Resztę policzymy.',
    lead: 'Trzy pola. Odpowiemy jak najszybciej.',
  },
  quote: {
    title: 'Zapytanie ofertowe',
    lead: 'Trzy pola. Odpowiemy jak najszybciej.',
    reply: 'Odpowiemy jak najszybciej.',
    fields: { contact: 'Osoba kontaktowa', email: 'Adres e-mail', service: 'Usługa', company: 'Nazwa firmy', phone: 'Telefon', cargo: 'Rodzaj ładunku' },
    servicePlaceholder: 'Wybierz usługę',
    submit: 'Wyślij zapytanie',
    success: { title: 'Dziękujemy. Zapytanie dotarło.', text: 'Opiekun zlecenia odezwie się jak najszybciej na podany adres e-mail lub telefon.' },
    errors: { required: 'To pole jest wymagane.', email: 'Podaj poprawny adres e-mail.' },
    flow: {
      title: 'Powiedz nam, czego potrzebujesz. Resztą zajmiemy się my.',
      lead: 'Trzy pola. Opiekun zlecenia odezwie się jak najszybciej.',
      after: ['Piszesz kilka słów o ładunku', 'Analizujemy trasę i wymagania', 'Odpowiadamy jak najszybciej z wyceną'],
      cardTitle: 'Poproś o wycenę',
      cardLead: 'Wystarczy kilka słów, resztę ustalimy w rozmowie.',
      service: 'Usługa',
      services: [
        { slug: 'transport', name: 'Transport', icon: 'truck' },
        { slug: 'magazynowanie', name: 'Magazynowanie', icon: 'warehouse' },
        { slug: 'spedycja', name: 'Spedycja', icon: 'ship' },
        { slug: 'clo', name: 'Obsługa celna', icon: 'customs' },
      ],
      who: 'Imię i nazwisko', whoPh: 'np. Anna Kowal',
      reach: 'E-mail lub telefon', reachPh: 'np. anna@firma.pl lub +48 600 000 000',
      desc: 'Czego dotyczy zapytanie', descPh: 'np. 12 palet komponentów z Gliwic do Brna, raz w tygodniu',
    },
  },
  about: {
    title: 'Japońska precyzja. Śląski adres.',
    lead: 'Meiko Trans Polska jest częścią grupy Meiko Trans Co., Ltd. z Nagoi, która od 1949 roku prowadzi operacje logistyczne w Azji, Ameryce i Europie. W Polsce działamy od 2005 roku.',
    group: {
      title: 'Grupa Meiko',
      text: 'Spółka matka Meiko Trans Co., Ltd. powstała 22 stycznia 1949 roku w Nagoi. Dziś grupa ma oddziały w Japonii, Stanach Zjednoczonych, Meksyku, Europie, Indiach, Tajlandii, Chinach, Wietnamie i Hongkongu. Polski oddział obsługuje klientów z całej Europy z Katowickiej Specjalnej Strefy Ekonomicznej.',
      facts: [{ label: 'Założona', value: '22.01.1949' }, { label: 'Siedziba grupy', value: 'Nagoja, Japonia' }, { label: 'W Polsce od', value: '2005' }, { label: 'Lokalizacje w Polsce', value: 'Gliwice, Dąbrowa Górnicza' }],
    },
    timelineTitle: 'Od lokalnego oddziału do hubu logistycznego',
    timeline: [
      { era: '2005-2016', title: 'Budowa fundamentów', text: 'Otwarcie oddziału w Gliwicach i start operacji magazynowych oraz spedycyjnych.' },
      { era: '2018-2023', title: 'Jakość i kompetencje celne', text: 'Certyfikacja ISO 9001, status AEO, własna agencja celna i skład celny.' },
      { era: '2025-2027', title: 'Inwestycje i technologia', text: 'Budowa trzeciego magazynu w Dąbrowie Górniczej, rozwój systemów cyfrowych dla klientów i kierowców.' },
    ],
    valuesTitle: 'Wartości, które przywieźliśmy z Japonii',
    valuesLead: 'Nie hasła na ścianie, lecz sposób pracy: dokładność, odpowiedzialność i długie relacje.',
    values: [
      { kanji: '絆', romaji: 'kizuna', meaning: 'Więź. Relacje z klientami budujemy na lata, nie na jedno zlecenie.' },
      { kanji: 'おもてなし', romaji: 'omotenashi', meaning: 'Gościnność. Przewidujemy potrzeby, zanim zostaną wypowiedziane.' },
      { kanji: '誠実', romaji: 'seijitsu', meaning: 'Uczciwość. Mówimy, co możemy zrobić, i robimy to, co powiedzieliśmy.' },
      { kanji: '和', romaji: 'wa', meaning: 'Harmonia. Zespół, przewoźnicy i klient pracują w jednym rytmie.' },
      { kanji: '信頼', romaji: 'shinrai', meaning: 'Zaufanie. Zdobywane każdą dostawą, potwierdzane audytami.' },
    ],
    network: {
      title: 'Globalna sieć, lokalna wiedza',
      lead: 'Jedno zintegrowane rozwiązanie na trzech kontynentach.',
      regions: [
        { name: 'Japonia', cities: 'Nagoja, Tokio, Osaka, Kobe, Fukuoka, Sendai, Hamamatsu' },
        { name: 'Ameryka Północna', cities: 'Los Angeles, Chicago, Houston, Atlanta, Ohio, Karolina Południowa' },
        { name: 'Meksyk', cities: 'Guanajuato' },
        { name: 'Europa', cities: 'Antwerpia, Grobbendonk, Düsseldorf, Hamburg' },
        { name: 'Polska', cities: 'Gliwice, Dąbrowa Górnicza' },
        { name: 'Indie', cities: 'Chennai, Gurgaon' },
        { name: 'Tajlandia', cities: 'Bangkok, Laem Chabang, Suvarnabhumi' },
        { name: 'Chiny i Hongkong', cities: 'Szanghaj, Kanton, Suzhou, Hongkong' },
        { name: 'Wietnam', cities: 'Hanoi, Ho Chi Minh' },
      ],
    },
  },
  quality: {
    title: 'Jakość i certyfikaty',
    lead: 'Certyfikat ISO 9001:2015, pozwolenie AEO i polityka jakości podpisana przez zarząd. Kliknij dokument, aby zobaczyć oryginał. Poniżej, co z nich wynika dla klienta.',
    outcomesTitle: 'Co to oznacza w praktyce',
    outcomes: [
      { title: 'Powtarzalna jakość', text: 'Każde zlecenie przechodzi te same punkty kontrolne, niezależnie od tego, kto je obsługuje.' },
      { title: 'Udokumentowane procesy', text: 'Procedury spisane, audytowane i aktualizowane. Nowy pracownik pracuje według tych samych zasad.' },
      { title: 'Ciągłe doskonalenie', text: 'Mierzymy terminowość i błędy, a wyniki przekładamy na zmiany w procesie.' },
      { title: 'Bezpieczeństwo celne', text: 'Status AEO wymaga kontroli dostępu, ewidencji i zabezpieczeń łańcucha dostaw. Spełniamy je na co dzień.' },
      { title: 'Zgodność z przepisami', text: 'Pełna zgodność z prawem celnym i podatkowym, potwierdzana przez administrację celną.' },
      { title: 'Zaufany operator', text: 'Organy celne traktują AEO jako partnera o niskim ryzyku. Dla klienta to mniej kontroli i przestojów.' },
      { title: 'Szybsze odprawy', text: 'Uproszczenia celne i priorytet obsługi skracają czas od granicy do magazynu.' },
      { title: 'Zarządzanie ryzykiem', text: 'Ryzyka operacyjne identyfikujemy z wyprzedzeniem i mamy dla nich plany działania.' },
    ],
  },
  contact: {
    title: 'Kontakt',
    lead: 'Wybierz dział albo lokalizację. Odpowiadamy w godzinach 8:00-16:00 w dni robocze.',
    locationsTitle: 'Lokalizacje',
    locations: [
      { name: 'Siedziba i Magazyn 1 · Gliwice', address: 'ul. Leona Wyczółkowskiego 121, 44-109 Gliwice' },
      { name: 'Magazyn 2 · Gliwice', address: 'ul. Gaudiego 6D, 44-109 Gliwice' },
      { name: 'Magazyn 3 · Dąbrowa Górnicza (w budowie)', address: 'ul. Innowacyjna, 42-520 Dąbrowa Górnicza' },
    ],
  },
  footer: {
    legal: 'Meiko Trans Polska Sp. z o.o. · KRS, NIP i REGON do uzupełnienia przed publikacją',
    docs: ['Polityka prywatności', 'Polityka cookies', 'Dane rejestrowe'],
    pagesTitle: 'Strony',
    docsTitle: 'Dokumenty',
    langTitle: 'Język',
    note: 'Część grupy Meiko Trans Co., Ltd., Nagoja, Japonia.',
    address: 'ul. Leona Wyczółkowskiego 121, 44-109 Gliwice',
  },
  faqTitle: 'Pytania i odpowiedzi',
  approval: { tooltip: 'Wartość przykładowa, do zatwierdzenia przed publikacją', legend: 'wartość do zatwierdzenia' },
  notFound: { title: 'Nie ma takiej strony.', text: 'Adres mógł się zmienić. Wróć na stronę główną i wybierz z menu.' },
};
